[2025-03-01T09:32:34.494+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T09:32:34.532+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_scrapper_pipeline.insert_csv manual__2025-03-01T09:31:16.279784+00:00 [queued]>
[2025-03-01T09:32:34.548+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_scrapper_pipeline.insert_csv manual__2025-03-01T09:31:16.279784+00:00 [queued]>
[2025-03-01T09:32:34.550+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T09:32:34.572+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_csv> on 2025-03-01 09:31:16.279784+00:00
[2025-03-01T09:32:34.588+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=478) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-01T09:32:34.590+0000] {standard_task_runner.py:72} INFO - Started process 484 to run task
[2025-03-01T09:32:34.590+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_scrapper_pipeline', 'insert_csv', 'manual__2025-03-01T09:31:16.279784+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpl8aykv3n']
[2025-03-01T09:32:34.592+0000] {standard_task_runner.py:105} INFO - Job 203: Subtask insert_csv
[2025-03-01T09:32:34.666+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_scrapper_pipeline.insert_csv manual__2025-03-01T09:31:16.279784+00:00 [running]> on host 18f96a44278a
[2025-03-01T09:32:34.778+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_scrapper_pipeline' AIRFLOW_CTX_TASK_ID='insert_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T09:31:16.279784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T09:31:16.279784+00:00'
[2025-03-01T09:32:34.780+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-01T09:32:34.781+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-01T09:32:34.782+0000] {logging_mixin.py:190} INFO - Current task name:insert_csv state:running start_date:2025-03-01 09:32:34.533237+00:00
[2025-03-01T09:32:34.782+0000] {logging_mixin.py:190} INFO - Dag name:etl_scrapper_pipeline and current dag run status:running
[2025-03-01T09:32:34.783+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T09:32:34.785+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dags.py", line 160, in insert_csv_to_postgres
    raise FileNotFoundError(f"File {file_path} tidak ditemukan!")
FileNotFoundError: File /opt/***/dags/cleaned_data.csv tidak ditemukan!
[2025-03-01T09:32:34.810+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-01T09:32:34.811+0000] {logging_mixin.py:190} INFO - Task start:2025-03-01 09:32:34.533237+00:00 end:2025-03-01 09:32:34.809501+00:00 duration:0.276264
[2025-03-01T09:32:34.811+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_csv> dag:<DAG: etl_scrapper_pipeline> dagrun:<DagRun etl_scrapper_pipeline @ 2025-03-01 09:31:16.279784+00:00: manual__2025-03-01T09:31:16.279784+00:00, state:running, queued_at: 2025-03-01 09:31:16.299659+00:00. externally triggered: True>
[2025-03-01T09:32:34.812+0000] {logging_mixin.py:190} INFO - Failure caused by File /opt/***/dags/cleaned_data.csv tidak ditemukan!
[2025-03-01T09:32:34.813+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_scrapper_pipeline, task_id=insert_csv, run_id=manual__2025-03-01T09:31:16.279784+00:00, execution_date=20250301T093116, start_date=20250301T093234, end_date=20250301T093234
[2025-03-01T09:32:34.859+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T09:32:34.860+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 203 for task insert_csv (File /opt/***/dags/cleaned_data.csv tidak ditemukan!; 484)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dags.py", line 160, in insert_csv_to_postgres
    raise FileNotFoundError(f"File {file_path} tidak ditemukan!")
FileNotFoundError: File /opt/***/dags/cleaned_data.csv tidak ditemukan!
[2025-03-01T09:32:34.887+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-01T09:32:34.926+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T09:32:34.929+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
