[2025-03-01T09:31:19.417+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T09:31:19.444+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_scrapper_pipeline.wait_for_raw_file manual__2025-03-01T09:31:16.279784+00:00 [queued]>
[2025-03-01T09:31:19.456+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_scrapper_pipeline.wait_for_raw_file manual__2025-03-01T09:31:16.279784+00:00 [queued]>
[2025-03-01T09:31:19.457+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T09:31:19.474+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_raw_file> on 2025-03-01 09:31:16.279784+00:00
[2025-03-01T09:31:19.484+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=440) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-01T09:31:19.486+0000] {standard_task_runner.py:72} INFO - Started process 450 to run task
[2025-03-01T09:31:19.488+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_scrapper_pipeline', 'wait_for_raw_file', 'manual__2025-03-01T09:31:16.279784+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmpkkciq4op']
[2025-03-01T09:31:19.489+0000] {standard_task_runner.py:105} INFO - Job 199: Subtask wait_for_raw_file
[2025-03-01T09:31:19.564+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_scrapper_pipeline.wait_for_raw_file manual__2025-03-01T09:31:16.279784+00:00 [running]> on host 18f96a44278a
[2025-03-01T09:31:19.717+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_scrapper_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_raw_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T09:31:16.279784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T09:31:16.279784+00:00'
[2025-03-01T09:31:19.724+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-01T09:31:19.724+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-01T09:31:19.725+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_raw_file state:running start_date:2025-03-01 09:31:19.444903+00:00
[2025-03-01T09:31:19.726+0000] {logging_mixin.py:190} INFO - Dag name:etl_scrapper_pipeline and current dag run status:running
[2025-03-01T09:31:19.726+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T09:31:19.727+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-03-01T09:31:19.744+0000] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-03-01T09:31:19.745+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:31:49.744+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:32:19.746+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:32:49.746+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:33:19.747+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:33:49.746+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:34:19.748+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:34:49.748+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:35:19.748+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:35:49.749+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:36:19.749+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/raw_data.csv
[2025-03-01T09:36:19.751+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 326, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 300.03517802399983 seconds exceeds the specified timeout of 300.0.
[2025-03-01T09:36:19.767+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-01T09:36:19.768+0000] {logging_mixin.py:190} INFO - Task start:2025-03-01 09:31:19.444903+00:00 end:2025-03-01 09:36:19.766397+00:00 duration:300.321494
[2025-03-01T09:36:19.768+0000] {logging_mixin.py:190} INFO - Task:<Task(FileSensor): wait_for_raw_file> dag:<DAG: etl_scrapper_pipeline> dagrun:<DagRun etl_scrapper_pipeline @ 2025-03-01 09:31:16.279784+00:00: manual__2025-03-01T09:31:16.279784+00:00, state:running, queued_at: 2025-03-01 09:31:16.299659+00:00. externally triggered: True>
[2025-03-01T09:36:19.769+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 300.03517802399983 seconds exceeds the specified timeout of 300.0.
[2025-03-01T09:36:19.769+0000] {taskinstance.py:1226} INFO - Immediate failure requested. Marking task as FAILED. dag_id=etl_scrapper_pipeline, task_id=wait_for_raw_file, run_id=manual__2025-03-01T09:31:16.279784+00:00, execution_date=20250301T093116, start_date=20250301T093119, end_date=20250301T093619
[2025-03-01T09:36:19.803+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T09:36:19.804+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 199 for task wait_for_raw_file (Sensor has timed out; run duration of 300.03517802399983 seconds exceeds the specified timeout of 300.0.; 450)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 326, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 300.03517802399983 seconds exceeds the specified timeout of 300.0.
[2025-03-01T09:36:19.848+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-01T09:36:19.884+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T09:36:19.886+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
