[2025-03-01T09:32:34.799+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-01T09:32:34.836+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_scrapper_pipeline.send_to_email manual__2025-03-01T09:31:16.279784+00:00 [queued]>
[2025-03-01T09:32:34.853+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_scrapper_pipeline.send_to_email manual__2025-03-01T09:31:16.279784+00:00 [queued]>
[2025-03-01T09:32:34.854+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-01T09:32:34.876+0000] {taskinstance.py:2890} INFO - Executing <Task(EmailOperator): send_to_email> on 2025-03-01 09:31:16.279784+00:00
[2025-03-01T09:32:34.889+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-01T09:32:34.891+0000] {standard_task_runner.py:72} INFO - Started process 486 to run task
[2025-03-01T09:32:34.892+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_scrapper_pipeline', 'send_to_email', 'manual__2025-03-01T09:31:16.279784+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/etl_dags.py', '--cfg-path', '/tmp/tmponqnhkbd']
[2025-03-01T09:32:34.894+0000] {standard_task_runner.py:105} INFO - Job 204: Subtask send_to_email
[2025-03-01T09:32:34.962+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_scrapper_pipeline.send_to_email manual__2025-03-01T09:31:16.279784+00:00 [running]> on host 18f96a44278a
[2025-03-01T09:32:35.071+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_scrapper_pipeline' AIRFLOW_CTX_TASK_ID='send_to_email' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T09:31:16.279784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T09:31:16.279784+00:00'
[2025-03-01T09:32:35.074+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-01T09:32:35.075+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-01T09:32:35.075+0000] {logging_mixin.py:190} INFO - Current task name:send_to_email state:running start_date:2025-03-01 09:32:34.837202+00:00
[2025-03-01T09:32:35.076+0000] {logging_mixin.py:190} INFO - Dag name:etl_scrapper_pipeline and current dag run status:running
[2025-03-01T09:32:35.076+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-01T09:32:35.079+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 142, in send_email_smtp
    msg, recipients = build_mime_message(
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 210, in build_mime_message
    with open(fname, "rb") as file:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/cleaned_data.csv'
[2025-03-01T09:32:35.096+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-01T09:32:35.097+0000] {logging_mixin.py:190} INFO - Task start:2025-03-01 09:32:34.837202+00:00 end:2025-03-01 09:32:35.096096+00:00 duration:0.258894
[2025-03-01T09:32:35.098+0000] {logging_mixin.py:190} INFO - Task:<Task(EmailOperator): send_to_email> dag:<DAG: etl_scrapper_pipeline> dagrun:<DagRun etl_scrapper_pipeline @ 2025-03-01 09:31:16.279784+00:00: manual__2025-03-01T09:31:16.279784+00:00, state:running, queued_at: 2025-03-01 09:31:16.299659+00:00. externally triggered: True>
[2025-03-01T09:32:35.099+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/dags/cleaned_data.csv'
[2025-03-01T09:32:35.100+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_scrapper_pipeline, task_id=send_to_email, run_id=manual__2025-03-01T09:31:16.279784+00:00, execution_date=20250301T093116, start_date=20250301T093234, end_date=20250301T093235
[2025-03-01T09:32:35.141+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-01T09:32:35.142+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 204 for task send_to_email ([Errno 2] No such file or directory: '/opt/airflow/dags/cleaned_data.csv'; 486)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 142, in send_email_smtp
    msg, recipients = build_mime_message(
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 210, in build_mime_message
    with open(fname, "rb") as file:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/cleaned_data.csv'
[2025-03-01T09:32:35.188+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-01T09:32:35.230+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T09:32:35.232+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
